/*
    Program to generate a PostScript (PS) file for visualizing the morphological pattern.

    Copyright (C) 2020  Abhinav Roy, M.P. Gururajan

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.


*/
#include<stdio.h>
#include<stdlib.h>

void ps_file(char* file_name, char* ps_file_name, int Nx, int Ny, int N)
{
  FILE *fp;
  int i,j;
  int temp;
  double *c;

  c = (double*)malloc((size_t)Nx*Ny* sizeof(double));

  if ((fp = fopen(file_name,"rb")) == NULL)
  {
    printf("Unable to open data file. Exiting.");
    exit(0);
  }
  else
  {
    fp = fopen(file_name,"rb");
  }

  fread(&c[0], sizeof(double),(size_t) Nx*Ny, fp);
  (void) fclose(fp);
  fflush(fp);
  if ((fp = fopen(ps_file_name,"wb")) == NULL)
  {
    printf("Unable to open ps file. Exiting.");
    exit(0);
  }
  else
  {
    fp = fopen(ps_file_name,"wb");
  }
/** The preamble to the ps file **/

fprintf(fp,"%%%%Generated by C-program output.\n");
fprintf(fp,"%%%%Creator: Abhinav Roy, MP Gururajan.\n");
fprintf(fp,"%%%%Title: Microstructure\n");
fprintf(fp,"%%%%BoundingBox: 0 0 256 256\n");
fprintf(fp,"0 0 translate\n");
fprintf(fp,"0 rotate\n");
fprintf(fp,"256 256 scale\n");
fprintf(fp,"/picstr %d string def\n",N);
fprintf(fp,"%d %d 8 [%d 0 0 -%d 0 %d]\n",N,N,N,N,N);
fprintf(fp,"{currentfile picstr readhexstring pop} image\n");
  //Generating the ps file
  for(i=0; i < Nx; ++i)
  {
	   for(j=0; j < Ny; ++j)
     {
		     temp = (int)(255.0*c[j+Ny*i]);
		     if(temp < 0)
			{ temp = 1;}
		     if(temp > 255)
			{temp = 255;}
		     fprintf(fp,"%02x",temp);
	}
	fprintf(fp,"\n");
 }

fprintf(fp,"grestore\n");
fprintf(fp,"showpage\n");
fprintf(fp,"%%%%EOF\n");
(void) fclose(fp);
 fflush(fp);
 free(c);

}
